### PR TITLE
Merge the provided authority/clientid with the config object. Add redirectUri as part of PCA factory overload.

### LINKED ISSUE #890: Hard crash when clientId is null
When calling PublicClientApplication.create(context, clientid, listener) w/o going through the typical example of providing a config resource file, the app has a hard crash because the OperationalParameters are not being updated with the provided clientId, so line 252 in OperationParameters.java (getClientId().hashCode()) is bombing due to a null exception.  Ideally, at least from my perspective, in the main create() in PublicClientApplication.java after (or during) line 854 (params = OperationParamatersAdapter.createOperationParameters) the clientId and authority should be replaced with any value provided to the method...in addition to sanity checks in OperationParameters.

### PR DESCRIPTION
**Pull request by rpdome**
Fix #890 

Two issues here.
1. PCA is not honoring authority/clientID before it makes a call to get device mode. Since no configuration file is passed. clientID will be null and exception is thrown.
2. redirectURI is also not there. Given that there are more than one default redirectURI format (broker Redirect URI was introduced as part of MSAL 1.0), we decided that this should be passed explicitly (instead of trying to prefill it).

### CODE REVIEW

File: msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java [hunk 1]
```diff
@@ -247,6 +247,7 @@ public static void create(@NonNull final Context context,
                 initializeConfiguration(context, configFileResourceId),
                 null, // client id
                 null, // authority
+                null,
```
Comment (kreedula) [inline msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java]: nit: add `// redirectUri` as a comment for readability like above

File: msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java [hunk 2]
```diff
@@ -285,44 +285,8 @@ public static void create(@NonNull final Context context,
...
-        validateNonNullArgument(context, NONNULL_CONSTANTS.CONTEXT);
-        validateNonNullArgument(clientId, NONNULL_CONSTANTS.CLIENT_ID);
-        validateNonNullArgument(listener, NONNULL_CONSTANTS.LISTENER);
-
-        create(
-                initializeConfiguration(context),
-                clientId,
-                null, // authority
+                null, // authority,
+                null,
```
Comment (kreedula) [inline msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java]: same

File: msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java [hunk 3]
```diff
@@ -849,8 +815,23 @@ private static ISingleAccountPublicClientApplication createSingleAccountPublicCl
     private static void create(@NonNull final PublicClientApplicationConfiguration config,
                                @Nullable final String clientId,
                                @Nullable final String authority,
+                               @Nullable final String redirectUri,
                                @NonNull final ApplicationCreatedListener listener) {
+        if (clientId != null) {
```
Comment (kreedula) [inline msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java]: why `null` checks here, since we are already validating in public api's above.

File: msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java [hunk 4]
```diff
@@ -768,6 +733,7 @@ private static IPublicClientApplication create(
         final ResultFuture<AsyncResult<IPublicClientApplication>> future = new ResultFuture<>();
         create(configuration,
                 null, // client id
+                null,
```
Comment (kreedula) [inline msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java]: same

File: msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java (hunk 3 above)
Comment (rpdome) [reply msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java]: Some API are not passing this value (i.e. the one that only takes config file).

Comment (rpdome) [reply msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java]: Basically, this function is an 'end point' of all PCA factory API.

Comment (kreedula) [reply msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java]: shouldn't we throw here if it's null then?

Comment (kreedula) [reply msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java]: you mean we will get from config if it's null here ?

Comment (rpdome) [reply msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java]: yes

Comment (rpdome) [reply msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java]: for this function, config is @Nonnull. The caller is responsible for generating the default config file if it's not passed by the app.
